const Projects = {
    Details:{//adding in opposite-chronological order, so it's easy to add later
        Template: {
            ID: "Template",
            Name: "",
            SmallDescription: "",
            LargeDescription: "",
            DownloadLink: "",
            EmbedVideoLinkID: "",
            NoOfProjectImages: 1
        },
        SpeedManiac: {
            ID: "SpeedManiac",
            Name: "Speed Maniac",
            SmallDescription: "Multiplayer, Lighting, Unity3D, Timeline, Photon, Racing",
            LargeDescription: "• Speed Maniac is a PVP arcade-style multiplayer racing game with a maximum of 5 players in one racing room.<br> • This was the Team project for the 5th Semester in college where I chose Multiplayer programming as the suitable position for me.",
            EmbedVideoLinkID: "Ru0wdiwoDeA",
            NoOfProjectImages: 6
        },
        TheApocalypse: {
            ID: "TheApocalypse",
            Name: "The Apocalypse",
            SmallDescription: "Windows,Unreal Engine, AI, TPS",
            LargeDescription: "• I always wanted to create a game like last of us, but with more survival mechanics, here is what I came up with, will love your opinions!!<br> •Made in Unreal Engine 4 with the only blueprints system.<br> •ps:- Models and Animations, not by me, just the logic and mechanics!",
	    EmbedVideoLinkID: "iMY6l-vYwRg",
            NoOfProjectImages: 5
        },
        TheWasteland: {
            ID: "TheWasteland",
            Name: "The Wasteland",
            SmallDescription: "Android,IOS, Unity, Endless Runner, Shooter",
            LargeDescription: "• The first-year project was an endless runner game with the shooting mechanics<br> • Platforms are autogenerated with tweakable values of distance. <br> • Speed of the character increases as the time increases.<br> • Currency system and Shopping system for the characters.<br> • Saving system for the highscore as well as currency and saved characters.",
	    EmbedVideoLinkID: "jODMhuTHlzw",
            NoOfProjectImages: 7
        },
	       GameJam: {
            ID: "GameJam",
            Name: "Two Day Game Jam",
            SmallDescription: "Unity, Puzzle, TPP, C#",
            LargeDescription: "• This was the result of 2 days of Game Competition where I was a lead developer with other 3 people.<br>• Enemies pathfinding was setup with Unity navigation system.<br>• Post processing was used with default render pipeline(Other render pipelines were not available).<br> • Worked on implementation of lighting, movement, AI, Puzzle and Inventory Mechanics as well as level design.",
	    EmbedVideoLinkID: "8SEobaihl1o",
            NoOfProjectImages: 6
        },
        TWLevelDesign: {
            ID: "TWLevelDesign",
            Name: "TW LevelDesign",
            SmallDescription: "Level Design, Lighting, Unity3D, Timeline",
            LargeDescription: "• This was the updated level design of The Wasteland game, where I have implemented post-processing, timeline for maximum quality.",
            EmbedVideoLinkID: "BO0MTTzkGj4",
            NoOfProjectImages: 1
        },
    }
};
